### ISSUE TITLE
Configured debug type 'tizentv' is not supported.

### ISSUE THREAD

**Issue by jfrux** [Samsung/vscode-extension-tizentv#25]
I have the extension installed but it does not work?
![image](https://user-images.githubusercontent.com/171077/111627441-6f448280-87c5-11eb-9927-8eae31526db1.png)
![image](https://user-images.githubusercontent.com/171077/111627537-87b49d00-87c5-11eb-9e20-130852c40c7f.png)

**Comment by juliengloria** [comment]
+1

**Comment by prozanne** [comment]
Hi, sorry for inconvenience.
The feature didn't support in this extension.
Since the guide was out-dated, I updated it to the latest version.

https://samsung.github.io/vscode-extension-tizentv/

The concept of the debug feature is just launching application with the chrome inspector. (Not related with launch.json)
You can use "Tizen TV: Debug Application" command to use "debug mode".
https://samsung.github.io/vscode-extension-tizentv/#supported-features

To use the feature, It's required to be set "tizentv.chromeExecutable" in your settings.json.

Thanks.
